# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UrlTrace < Formula
  desc "Extract the URLs an application actually uses, for whitelist policies"
  homepage "https://github.com/gjwnssud/url-trace"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.4.0/url-trace_0.4.0_darwin_amd64.tar.gz"
      sha256 "f31c8369051735ad8dd56f098def874418d22a86b9e44538714f7471d30f8169"

      define_method(:install) do
        bin.install "url-trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.4.0/url-trace_0.4.0_darwin_arm64.tar.gz"
      sha256 "83fc5c5e5a22a3c261b8ebe8389ad7be544c94f9247a0db0cdaace6377abab47"

      define_method(:install) do
        bin.install "url-trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.4.0/url-trace_0.4.0_linux_amd64.tar.gz"
      sha256 "a38951301be58e14097ca502806e20d520a14b7d0f2ccc46a9650d2f7f5418d6"
      define_method(:install) do
        bin.install "url-trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.4.0/url-trace_0.4.0_linux_arm64.tar.gz"
      sha256 "9af7ec00216c796ed7d1c0d7f62536cf98136bbfebe97edbcff999a09de27bcf"
      define_method(:install) do
        bin.install "url-trace"
      end
    end
  end

  test do
    system "#{bin}/url-trace", "--version"
  end
end
