# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UrlTrace < Formula
  desc "Extract the URLs an application actually uses, for whitelist policies"
  homepage "https://github.com/gjwnssud/url-trace"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.5.0/url-trace_0.5.0_darwin_amd64.tar.gz"
      sha256 "878758ede32deba802c5e47f65ede9e49de25a1c78ae9e25dfaf867235e5e421"

      define_method(:install) do
        bin.install "url-trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.5.0/url-trace_0.5.0_darwin_arm64.tar.gz"
      sha256 "1d54b02da4ef3fede39c6a832e2f231aeb79615e9966104326151713772c84cd"

      define_method(:install) do
        bin.install "url-trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.5.0/url-trace_0.5.0_linux_amd64.tar.gz"
      sha256 "c69579e41c83b8fdbdcbd52c21b24c8ef20fc28285707963298d5ac42797cdc6"
      define_method(:install) do
        bin.install "url-trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gjwnssud/url-trace/releases/download/v0.5.0/url-trace_0.5.0_linux_arm64.tar.gz"
      sha256 "e09cc62171ddb1810b85a7a11e36a957449a2404c9b3aef5ceef04cd4ddbc41f"
      define_method(:install) do
        bin.install "url-trace"
      end
    end
  end

  test do
    system "#{bin}/url-trace", "--version"
  end
end
